
#https://developers.cloudflare.com/workers/wrangler/configuration/

name = "birdle"
type = "webpack"

account_id = "2b41aaa8684b2a75f291109adfb626ba"
workers_dev = true
route = "birdle.isnow.online/*"
compatibility_date = "2022-02-08"
main="./workers-site/index.js"


kv-namespaces = [
    #{ binding = "gamedata_1", id = "9289b8a9cadd4123a54a8ee243c7baa0", preview_id = "e62d9b0ea478415abeaf90ce28f30f33" }
]



[dev]
  ip = "192.168.0.14"
  port = 4321
  local_protocol = "http"



[site]
bucket = "./public"


